Sonar reporting separately from Docker build
and not during Docker build
but using the SonarScanner CLI Docker image

diff --git a/{{cookiecutter.project_slug}}/Dockerfile b/{{cookiecutter.project_slug}}/Dockerfile
--- a/{{cookiecutter.project_slug}}/Dockerfile
+++ b/{{cookiecutter.project_slug}}/Dockerfile
@@ -4,22 +4,8 @@ FROM python:3.8-slim-buster as build
 # Variables defined with ARG can be modified when building the Docker image
 # --> see docker build --build-arg
 
-# Sonar-Scanner (SonarQube client) configuration
-# Enable/disable sonar reporting
-ARG SONAR=True
-ARG SONARHOST=sonarqube
-ARG SONARPORT=9000
-# Disable/enable sonarqube's version control support
-# check that .dockerignore does not exclude .git* files/directories if you want
-# to use version control support
-ARG SONARNOSCM=True
-# Installation directory for sonar-scanner
-ARG SONAR_SCANNER_HOME=/opt/sonar-scanner
-# sonar-scanner version, allows to control which version will be installed
-ARG SONAR_SCANNER_VERSION=4.4.0.2170
-# Define environment variables based on arguments
-# Add sonar-scanner executable to PATH for sonar reporting
-ENV PATH=${SONAR_SCANNER_HOME}/bin:${PATH}
+# Name of the code analyses report file
+ARG REPORTFILE=code-analyses.txt
 
 # pip environment variables: no version check, no caching
 ENV PIP_DISABLE_PIP_VERSION_CHECK=1
@@ -27,43 +13,20 @@ ENV PIP_NO_CACHE_DIR=1
 
 # Install debian packages required for sonar-scanner installation
 RUN apt-get update \
-    && apt-get install -y --no-install-recommends make ca-certificates wget unzip \
+    && apt-get install -y --no-install-recommends make \
     && rm -rf /var/lib/apt/lists/*
-
-# Install sonar-scanner, based on sonar-scanner-cli Dockerfile --> see docker hub
-WORKDIR /opt
-RUN if [ ${SONAR} = "True" ] ; then \
-    wget -U "scannercli" -q -O /opt/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip \
-    && unzip sonar-scanner-cli.zip \
-    && rm sonar-scanner-cli.zip \
-    && mv sonar-scanner-${SONAR_SCANNER_VERSION}-linux ${SONAR_SCANNER_HOME} ;fi
 
 # Copy Python app into image 
 WORKDIR /app
 COPY . .
 
-# Use Makefile in order to test/analyse and report results to SonarQube
-# Sonar analysis requires that SonarQube server is running (by default on 
-# host 'sonarqube' and port 9000, see Makefile).
-# This can easily be achieved by naming the SonarQube container 'sonarqube' and
-# building this image within the same (docker) network where the 'sonarqube'
-# container is running.
-# SONARNOSCM controls SonarQube's version control support (e.g., for git) in
-# case you do not want to copy the actual repository (.git/) into the image
-# for building (also see Makefile and .dockerignore, SONARNOSCM=True by default)
-# SONAR reporting can be disabled by passing --build-arg SONAR=False
-# only unit tests will be run in this case
-# Note that the build won't fail if unit tests fail (in both cases)
-RUN if [ ${SONAR} = "True" ] ; then \
-    make clean-all \
-    && make install-dev \
-    && make sonar SONARHOST=${SONARHOST} SONARPORT=${SONARPORT} SONARNOSCM=${SONARNOSCM} \
-    ; else \
-    make clean-all \
-    && make install-dev \
-    && (make lint || exit 0) \
-    && make test \
-    ;fi
+# Use Makefile in order to test/analyse code
+# Docker build fails if unit tests fail
+RUN make clean-all && \
+    make install-dev && \
+    (make lint >${REPORTFILE} || exit 0) && \
+    make test >>${REPORTFILE}
+
 # Use Makefile in order to build a Python wheel from the app
 RUN make clean-all && make dist
 
@@ -78,6 +41,8 @@ FROM python:3.8-slim-buster
 # is defined as the Docker ENTRYPOINT (see below).
 ARG ENTRYPOINT
 ENV ENTRYPOINT=${ENTRYPOINT}
+# Name of the code analyses report file
+ARG REPORTFILE=code-analyses.txt
 # pip environment variables: no version check, no caching
 ENV PIP_DISABLE_PIP_VERSION_CHECK=1
 ENV PIP_NO_CACHE_DIR=1
@@ -99,10 +64,14 @@ COPY --from=build /app/dist/*.whl /dist/
 RUN pip install /dist/*.whl
 # Switch to working directory in user's home, dir exists due to useradd param
 WORKDIR /home/user/app
-# Copy entrypoint.sh script from build stage
+# Copy entrypoint.sh script from build stage 
 COPY --from=build /app/entrypoint.sh .
-# Change owner and access rights
-RUN chown user:user . ; chown user:user entrypoint.sh ; chmod a+x entrypoint.sh
+# Copy REPORTFILE from build stage 
+COPY --from=build /app/${REPORTFILE} .
+# Change owner
+RUN chown user:user . ; \
+    chown user:user entrypoint.sh; \
+    chown user:user ${REPORTFILE}
 # Switch user/set user for running the app
 USER user
 # Specify entrypoint in json style 
